language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: EaAAWXevwf7B7aG+Sizu7+0LSjpDeLjwKZpUX/PGnSQHHWdbSduQx6XmaJuxDu3s9jJdO8DpWUNV1JRbfq1Mz/GdvZKw8dDwu/D6k1yMC7crcOuDTPvcE/3PrC5MnfjNfBxFQMinUul4ep1AStzAn9NrbPcc6ZQ3XlMCbsfKpyznLQh0LfAhUjJcrQQTMytGce5yOHl156OawGkm9/njhNJ9nG7eLMzirRJ3sCIgKvmcFMbBYYAIfazTRCG33htYeVK+BKwF6J4QLx7TasnDY4WMYguMy2u78/q2OYkcJA2Qfr94794Iiub0XTWbiy7E7VY1Bc2xtRjh543sZakS+U288quFRyUOMfTzuqyAMeJ0DL9bI32B+xsZp/ZsQ9TCA6Wv1XaEBT8/+R3a9aji4Sr9/XqBy7OGZCvb2zeo/+XqcZEJHR6vyD5u51pDodxkzxxxTs1ndVJKM1r7Zr4KvvKQqkN9TQCwOXloJiILThlLWx4BnBduqnLRWdf0u+ngyj2JtJ3vSIuEp2O4QX5J8bCNaglI4ZwU+W7EkT85gTlyZawB57yoAr/j0XzVdjtv2+9Jl2rXQtnILlNjNDVdP4dUZEtsKdJwK7HHOI8X99OAe83iqWyl2zuWqRBQhaO+yLbT6gFygz8kABPYNOLzEH2FjBjHJwYWb+KL5sYh3mg=
  app: cisc3140summerwithpython
