language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  - provider: heroku
    api_key:
      secure: 0akubT7L9R0OYBCRQmOa158GrRLBq4nzq8T6kyj8FoFDtbqKbr+otHhYYQC8Lfdx3sbHfYcUgnGG1Ph3M+OIeDhfdlcYVzPcY+nfWRUJCw4xQ1vfvDBx6hu4GjXp1Dka3g5zfiYtWsmC53XH7snOZYBRNml8gwQYy6IYuCxFnUH+0tPuXQ6bzYcAetc8ThEPRVnWBIDY4qEujFypXYz73RvnyLtTYiDExC4Oy2OO8bQWAHDxbTbMOVRh9JuMaMeNsJchnNgF5NtEZq5mem6KDupt1IqkY7MidIgzOYfN+B/7hz2QjsPpQykMFwQ9nnB9fCAkJzI0xD9qH5LQSjBdfGFSx0g7TMDFPN9nQayOQZP3rlULilLOBrcAWqdY0fGnmb7kyZsNmTBQ9n6J6oEOBX0Vbp3Gd+zfJnqspBRBz+d+yMqJT7CLEz4RoNXBQTN0DMNqyCeIRwyA9JEd9VbUo6tuoPQ0DweVvS1Nn7zNS7I4pIhcbRIjaY8ThI3AM/itNPuYh8Xs13cEJfqKl/peqgb50eWnnJwSTyyTHJexfMVMc9Itn6tGls6hITnZ+P1SN2szXCNxZdMcLJ52ZzEKjOZ6EVkBEpspe+c3119PBjVrOWEGDqD+L6Cr/BssI8Ci6gioiU12s2L02UEfxWK6jrWqQIaZm3e1rKtWo9K2nvo=
    app: cisc3140summerwithpython