language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python3 -m unittest discover
deploy:
  - provider: heroku
  api_key:
    secure: Ro94MUNGcJfsmfddQpw2XldKJisUr50zD4R/JpUB4Yj61yZKe27bJzI+y//GO2a1+WdKn+ZvW/Dr+iDdGcB++ilRFKhHiFxs8VO2FTB7n+l74F+F5MEQ5nONqpUAuijEzqOQyfNC4WLhJVWqsBocePhr+gcbWFdQsV8VGiBi0rssPsOr6kIKCFdqC4rQ4zCJMF6PIA+FaoefYcW/f3eatJbsFpgOEmuYtghK+ZrneIsnNNBVrtAZA7ewn1k2mx2W2Eegy/owVqG1UaxbG0534HPd1OzAISY+RKisEimF64UskmBBEAqVp/uDQwwz6aiFHFqc7CTcV+/h162VnPnGTWDARffQuPBl7HtA4/RYe6R926lVeysWczRTvgBgdaL1JzwSGWs+iAkhuO3klaoNqlAor/BCjOucG9cpFGa2xckPJ4MNPT3NTxCiYlztVgaEYv4pmqI7PFa8duIs69aFReMTmpDFBedOSEw52vmQmVrpyYSo9Ieq5uZ8gifLXZrC+KBswzuFy4qQlShcyLCVNphFBtEn0bra5Bxh6LncGRJOVMxui9IRzQFxqoesOfSccP89qdf4k7ZlJCGBPTGkUdch0QWD6D0e+NyD0H9cKAtVmNTIMk74DXxOXNjgoyCjpxNtkBbXVtQ335+OoId0m++K2JrFSxYUoweOtoWyqzM=
  app: cisc3140summerwithpython