language: python
python:
- '3.7'
install:
- pip3 install -r requirements.txt
script:
- python -m unittest discover
deploy:
  - provider: heroku
    api_key:
    secure: XkDy9Yi05oEP9AGyDjNxgCsLdEwcVVX7Tdm7G4Ua+5NbAfAgvpgus1Vl4IAFtqhu9sUOd4iVNyVgBCGuVw3D6jX/sVA/sj9HH6UuYdXxlUi4enpBDfLR4ANkG2Ecrtfo1ZQt47pz1umo99kDRpL47fqIrPsWWpDtrhijHVdEC9NBibk3YSLFtwcwbuH0/E9ise0QB56xg62fzNQ7Sz9+kwJwgsQDtOmOtZRNWtqoJoQarfrRX10LyB+RTN26J3bT7iSTCcGbSFVqjd5Zf6uucvwGcGXTzEmh9lxqgR04nMRlNdiHDV5eJbX7kMIVfEqHaceX/7M9F7DW8fEqaR5H6akpjL/YWwxa0WHiqtUttLVqTDVlRIqT5H7Se9ax1aOw4LnHa+y969/CcuzFKQ7qBPIlTosdznNud2t9g3eU1fFFUkMwb3OGkkTgDXGB9SBK4McT5Doi8Ue3LtU0/rqQxQ1bFUqJnuDJacVrkjUqxDus+rRoVj3+/vhFtC4jJSMkkerKrxb9s72ntkKDAWqGqcDda5jlkAcM39u1pBuDNQ5NxspQV3u9j75DzausQKCjFIR9qq7rs5jP2R1vj6+oE1OAmUrvClLFnnuyVP3xdnTgXy24FUFHvC1kZ3FHzvtBEIDbbHLhl80G8LlZbvnuXauRiq9XXobe2ZzNtCm8dCg=
  app cisc3140summerfunwithpython